import { useState } from 'react'
import { Eye, EyeOff, GraduationCap, LockKeyhole, LogIn, Mail, ShieldCheck } from 'lucide-react'
import { apiFetch,setToken } from './api'
import './LoginPage.css'
export default function LoginPage({onLogin}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');try{const r=await apiFetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({email,password})});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{throw new Error('Máy chủ trả về dữ liệu không hợp lệ. Vui lòng kiểm tra cấu hình API.')}if(!r.ok)throw new Error(Object.values(d.errors??{}).flat()[0]??d.message??`Đăng nhập thất bại (${r.status}).`);if(!d.token||!d.user)throw new Error('Phản hồi đăng nhập không đầy đủ.');setToken(d.token);onLogin(d.user)}catch(x){setError(x.message)}finally{setLoading(false)}}
 return <div className="login-page"><div className="login-visual"><div className="login-brand"><span><GraduationCap size={30}/></span><div><b>TH-THCS THANH ĐÀM</b><small>Hệ thống quản lý nội bộ</small></div></div><div className="visual-copy"><span><ShieldCheck size={30}/></span><h1>Quản lý nhà trường<br/>thông minh, hiệu quả</h1><p>Kết nối công việc, giáo viên, KPI và dữ liệu trên một nền tảng bảo mật duy nhất.</p></div><div className="visual-dots"><i/><i/><i/></div></div><div className="login-form-side"><form onSubmit={submit}><div className="mobile-login-brand"><GraduationCap/></div><h2>Chào mừng trở lại</h2><p>Đăng nhập bằng tài khoản được nhà trường cấp</p>{error&&<div className="login-error">{error}</div>}<label>Email đăng nhập<div><Mail size={18}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div></label><label>Mật khẩu<div><LockKeyhole size={18}/><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><button className="login-submit" disabled={loading}><LogIn size={18}/>{loading?'Đang đăng nhập...':'Đăng nhập'}</button><small className="login-help">Liên hệ quản trị viên nếu bạn quên mật khẩu.</small></form></div></div>
}
